### ISSUE TITLE
change timbersaw to inferno

### ISSUE THREAD

**Issue by sukrosono** [TheEnigmaBlade/TreeTag#1]
hey dude i m very insterest in this game, and i just found it on the dotA reborn yesterday.
i like more the clasic game, i wanna try but i got no people want to play tree tag. i just wonder the balance if the inferno was changed to timbersaw. i wanna help with anything that i can do, but i dont know where to begin. teach me

**Comment by TheEnigmaBlade** [comment]
The player model, whether it's Timbersaw or Inferno, does not affect gameplay. It is purely visual.
